---
version: '3.9'
services:
  kafka-kraft:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka-kraft
    container_name: kafka-kraft
    restart: always
    ports:
      - '9101:9101'
      - '9092:9092'
      - '29092:29092'
    volumes:
      - ./temp_kafka:/var/lib/kafka/data
      - ./clusterID:/tmp/clusterID
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://kafka-kraft:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # change with number of kafka cluster
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-kraft:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'NqnEdODVKkiLTfJvqd1uqQ'

  kafka-connect-1:
    image: confluentinc/cp-kafka-connect:7.5.0
    hostname: kafka-connect-1
    container_name: kafka-connect-1
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - ./etc/jars:/etc/kafka-connect/jars
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://kafka-kraft:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-kraft
      CONNECT_REST_ADVERTISED_LISTENER: http
      CONNECT_REST_ADVERTISED_PORT: 8083
      # CONNECT_BOOTSTRAP_SERVERS: 10.0.0.7:29092,10.0.0.6:29092,10.0.0.5:29092
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: '/usr/share/java, /etc/kafka-connect/jars'
    depends_on:
      - kafka-kraft
      - schema-registry

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    restart: always
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://kafka-kraft:9092'
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_DEBUG: true
    depends_on:
      - kafka-kraft

  